blueprint:
  name: Fibaro SceneActivatie Cover bediening
  description: Gebruikt de SceneActivatie mogelijkheid om een cover in de juiste stand te zetten.
  domain: automation
  input:
    trigger:
      name: Schakelaar
      description: Het apparaat dat achter de fysieke schakelaar zit.
      selector:
        device:
    sa_value:
      name: Scene-activatienummer 
      description: Het nummer dat het de bewuste klik wordt doorgestuurd, bijvoorbeeld 10, 11, 14, 24, 16, 26 of 25.
    target:
      name: Doelapparaat
      description: De cover-controller die op het doelapparaat is aangespoten.
      selector:
        device:
    target_entity:
      name: Doelapparaat entity
      description: De juiste entity in deze cover-controller.
      selector:
        entity:
          domain: cover
    position:
      name: Positie 
      description: De gewenste stabnd van het doelapparaat (0 is helemaal dicht, 100 is helemaal open).
trigger:
- platform: device
  device_id: !input trigger
  domain: zwave_js
  type: event.value_notification.scene_activation
  property: sceneId
  property_key:
  endpoint: 0
  command_class: 43
  subtype: Endpoint 0
  value: !input sa_value
condition: []
action:
- device_id: !input target
  domain: cover
  entity_id: !input target_entity
  type: set_position
  position: !input position
mode: single
